version: "3.9"

services:
    app:
        container_name: resque
        image: resque:latest
        restart: unless-stopped
        build:
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - ./:/var/www/resque:rw

    redis:
        container_name: resque-redis
        image: redis:7.0-alpine
        volumes:
            - redis:/data:rw

volumes:
    redis:
